name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: phamthanhtung35nb
          outputs: |
            dist/snake.svg?palette=github
            dist/snake-dark.svg?palette=github-dark&color_dots=#161b22,#21262d,#30363d,#40464d,#39d353&color_empty=#2d333b
            dist/snake-light.svg?palette=github-light
            dist/snake-neon.svg?palette=github-dark&color_snake=#7c3aed&color_dots=#1a1a2e,#16213e,#0f3460,#533483,#7c3aed&color_empty=#2d333b

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}